include:
  - project: 'pedropilla/pipelines'
    ref: main
    file: '/ci-templates.yml'

variables:
  APP_NAME: "api-usermgmt"
  DOCKER_BUILD_PATH: "."
  ENVIRONMENT: "dev"

test-app:
  extends: .test-app-template
  tags:
  - k8s-gitlab-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-docker-image:
  extends: .build-docker-image-template
  tags:
  - k8s-gitlab-runner
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-app:
  extends: .deploy-app-template
  variables:
    CONTEXT: "rancher-desktop"
    KUSTOMIZE_DIR: "./kustomize/overlays/dev"
    KUBECONFIG: "~/.kube/config"
