apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-usermgmt
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-usermgmt
        env:
        - name: ENV
          value: "stg"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-usermgmt
  annotations:
    external-dns.alpha.kubernetes.io/hostname: stg.api-usermgmt.fullstack.pw
spec:
  tls:
  - hosts:
    - stg.api-usermgmt.fullstack.pw
    secretName: fullstack-tls
  ingressClassName: traefik
  rules:
  - host: stg.api-usermgmt.fullstack.pw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-usermgmt
            port:
              number: 8080
