apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-usermgmt
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-usermgmt
        env:
        - name: ENV
          value: "dev"
