name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
    docker-build-and-push:
      name: Build and Push App
      uses: fullstack-pw/pipelines/.github/workflows/build-and-push.yml@main
      with:
          app-context: "."
          app-name: "api-usermgmt"

    sandbox-deploy:
      needs: docker-build-and-push
      name: Deploy Application
      uses: fullstack-pw/pipelines/.github/workflows/deploy-kustomize.yml@main
      with:
        kustomize-dir: "kustomize/overlays/sandbox"
        context: "kubernetes-admin@kubernetes"
        app-name: api-usermgmt

    cypress-tests:
      needs: sandbox-deploy
      name: Run Cypress Tests
      uses: fullstack-pw/pipelines/.github/workflows/cypress.yml@main
      with:
        app-url: "https://api-usermgmt.fullstack.pw"