name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    docker-build-and-push:
      name: Build and Push App
      uses: fullstack-pw/pipelines/.github/workflows/build-and-push.yml@main
      with:
          app-context: "."
          app-name: "api-usermgmt"

    dev-deploy:
      needs: docker-build-and-push
      name: Deploy Application
      uses: fullstack-pw/pipelines/.github/workflows/deploy-kustomize.yml@main
      with:
        kustomize-dir: "kustomize/overlays/dev"
        context: "kubernetes-admin@kubernetes"
        app-name: api-usermgmt